
# Server Configuration
server:
  port: 8080

# Logger format
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) - %-40.40c{1.}: %msg%n"  

# Spring Configuration  
spring:
  #Application Name
  application:
    name: Clients Microservice
  h2:
    console:
      enabled: true
      path: /h2-console
  #Persistence properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace 
  #Memory Data Source  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clients_microservice
    username: sa
    password: 